### ISSUE TITLE
cmake issues

### ISSUE THREAD

**Issue by hownot** [nepluno/SoapFilm3D#1]
I have a question.i used cmake, but an error has occurred. error is Files/CMake/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Eigen3 (missing: EIGEN3_INCLUDE_DIR EIGEN3_VERSION_OK)         
(Required is at least version "2.91.0")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindEigen3.cmake:77 (find_package_handle_standard_args)
  CMakeLists.txt:25 (find_package) and I referred to the https://github.com/nepluno/SoapFilm3D
  os : windows 10 cmake version 3.11.0 visual stdio version 2017

**Comment by raymondyfei** [comment]
You need download Eigen library before you compile. See [http://eigen.tuxfamily.org/index.php?title=Main_Page](http://eigen.tuxfamily.org/index.php?title=Main_Page) for more details
