### ISSUE TITLE
Segmentation fault upon running SoapFilm3D

### ISSUE THREAD

**Issue by altineller** [nepluno/SoapFilm3D#7]
Hello,

After building successfully, I have moved build/Apps/SoapFilm3D/SoapFilm3D into bin under SoalFilm3D directory and when I run:

bin/SoapFilm3D assets/foam.txt

I get a Segmentation fault (core dumped)

Best Regards.
Can

**Comment by altineller** [comment]
I have straced SoalFilm3D and:

openat(AT_FDCWD, "assets/twobubbles.txt", O_RDONLY) = 3
read(3, "scene\t\t\ttwobubbles\ntime-step\t\t0."..., 8191) = 684
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=NULL} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)


it seems that it is crashing reading the config file. Could this be an encoding problem too?

Best Regards,
Can

**Comment by raymondyfei** [comment]
The working directory should be exactly the directory containing `assets`. If so I'm not sure what's going on there. 

You may find the config file reader at `Options::parseOptionFile` in `SimOptions.cpp`, which is a pretty standard file reading function with `std::ifstream`. Maybe you can print something to find which line causes the crashing?

**Comment by altineller** [comment]
If the output-png* and output-mesh* lines from each config file is removed, the program works, showing a wireframe bubble, and runs the simulation when space is pushed.

Maybe I have a library missing relating to png export? Would it compile if dependencies were missing and raise a run time error?

I also had to copy Apps directory under assets, so it stopped complaining about not find the env and PR files.

![render](https://user-images.githubusercontent.com/2217584/161971000-e6391cd5-19a2-41d1-8fb7-6eef58810e05.png)

Also, in render mode 2 and 3, I got some black surfaces. Is this normal? I get a blank screen for render mode 1, and 1 and 4 works. (wireframe and 3d render in environment)

Best Regards,
Can

**Comment by raymondyfei** [comment]
The output-png is a deprecated feature and has already been removed. Do both the output-png and output-mesh have to be removed or does only output-png need to be removed to make it work?

The render modes 2 and 3 are also supposed to be deprecated and will be removed in the future version.

**Comment by altineller** [comment]
both of them need to be removed.

**Comment by nepluno** [comment]
> both of them need to be removed.

Thanks. Then maybe it's related to the `mkdir` operation that creates a directory on the machine. Is there a directory that was created correctly?
