### ISSUE TITLE
windows binaries missing libpng16.dll

### ISSUE THREAD

**Issue by altineller** [nepluno/SoapFilm3D#8]
Hello,

I also want to run it on windows, but however I don't have a compiler setup so I want to use the binaries.

It complains about libpng16.dll, and I find the responsible runtime distribution pack, but windows won't let me install the distribution pack quoting that it has been replaced by a newer runtime distribution and incompatible with windows 10.

Best Regards,
Can

**Comment by raymondyfei** [comment]
The latest version doesn't need libpng anymore. Close the issue.
